### ISSUE TITLE
Levels don't load after selecting PortalLevels.txt

### ISSUE THREAD

**Issue by realityfabric** [JonathanNiehenke/JS_Portal#1]
I tested the game in both Firefox and Chrome on Linux Mint.

I loaded Portal.html, clicked the button, and selected PortalLevels.txt, as instructed in the readme.

After this point nothing happened except for "No File Selected" changing to "PortalLevels.txt".

**Comment by realityfabric** [comment]
> ReferenceError: Engine is not defined [Learn More]  Portal.js:4:5

In Firefox on Ubuntu 16.04.

**Comment by realityfabric** [comment]
Copying TileEngine.js into the JS_TileEngine directory from this GitHub repository fixed the problem.

**Comment by realityfabric** [comment]
This was an issue with how I cloned the repository. Using ```git clone --recursive https://github.com/JonathanNiehenke/JS_Portal.git``` cloned the submodule that needed to be cloned.

Should the README include a warning about this being necessary?

**Comment by JonathanNiehenke** [comment]
Rather than bandaging the problem, the causing problem (the use of submodules) should be replace with perhaps subtrees. Of which I have even less familiar.

**Comment by realityfabric** [comment]
I don't think that informing users that they will need to download the dependencies either separately or using the ```--recursive``` flag with git is a bandaid. It's not that much extra work.

I'm not familiar with subtrees, either, but I will look into them since you are considering switching to them.
